# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 14.x
        cache: 'npm'
        cache-dependency-path: "./sample/package-lock.json"
    - name: CI
      run: npm ci
      working-directory: './sample'
    - name: Build
      run: npm run build --if-present
      working-directory: './sample'
    - name: Test
      run: npm test
      working-directory: './sample'
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3.7.3
      with:
        deploy_key: ${{ secrets.SECRET_KEY }}
        publish_branch: ph-pages
        publish_dir: ./docs
